---
- hosts: 127.0.0.1
  connection: local
  become: true

  roles:
    - application
    - docker-compose

  tasks:
    - name: "Add {{ app_fqdn }} to host file"
      shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
      tags:
        - test
        
    # Pause for 40 seconds to run mysql db on first deploy.
    - pause:
        seconds: 40

    - name: Checks if App is works correctly
      block:
        - name: Checks if it works       
          uri:
            url: "http://{{ item.fqdn }}:{{ item.port }}"
            return_content: yes
          register: this
          with_items: "{{ app }}"
          failed_when: "'555Widget News &copy; 2011. All rights reserved' not in this.content"
      tags:
        - test
      rescue:
        - name: Send notofication to Slack
          slack:
            token: TFBPBNB2L/BRQJATF9R/2zbm0nl8LNNtDszgOh4u7CF5
            msg: "App content not found"
            channel: "errors"
            username: "webhook"
            parse: "full"      
        - name: Import rollback playbook tasks
          include_tasks: rollback.yaml
