---
- hosts: 127.0.0.1
  connection: local
  become: true

  roles:
    - application
    - docker-compose

#    - name: "Add {{ app_fqdn }} to host file"
#      shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
#      tags:
#        - test

#    - uri:
#        url: "http://{{ app_fqdn }}"
#        return_content: yes
#      register: this
#      failed_when: "'Widget News &copy; 2011. All rights reserved' not in this.content"
#      tags:
#        - test
