---
- hosts: 127.0.0.1
  connection: local
  become: true

  roles:
    - application
    - docker-compose

  tasks:
    - name: "Add {{ app_fqdn }} to host file"
      shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
      tags:
        - test
        
    # Pause for 40 seconds to run mysql db on first deploy.
    - pause:
        seconds: 40
    
    - uri:
        url: "http://{{ app_fqdn }}:{{ app_port }}"
        return_content: yes
      register: this
      failed_when: "'Widget News &copy; 2011. All rights reserved' not in this.content"
      tags:
        - test
