- name: Run docker-compose 
  docker_compose:
    project_name: cms
    definition:
      version: "3"
      services:
        www:
          image: eboraas/apache-php
          ports:
<<<<<<< HEAD
            - "{{ item.src_port }}:{{ item.dst_port }}"
=======
            - "7878:80"
>>>>>>> 2970759fbd2d7746bf44f54b41e7da5df0ab7251
          volumes:
            - /opt/widgetnewscms:/var/www/html/
          depends_on:
            - db
          networks:
            - default
        db:
          image: mysql:5.7
          environment:
            MYSQL_DATABASE: cmsexample
            MYSQL_USER: cmsuser
            MYSQL_PASSWORD: jumperMysqlUserPass2020!
            MYSQL_ROOT_PASSWORD: jumperMysqlUserPass2020!
          volumes:
            - /opt/widgetnewscms/CMSExample.sql:/docker-entrypoint-initdb.d/1-CMSExample.sql
          networks:
            - default
  register: output
  with_items: "{{ app }}"  

- name: Debug
  debug:
    var: output

- name: Assert
  assert:
    that:
      - "www.cms_www_1.state.running"
      - "db.cms_db_1.state.running"
